In [1]:
import pandas as pd
import numpy as np

# compare intensitites

In [2]:
ddir = '/u/home/f/f7xiesnm/project-zipursky/easifish/lt186/outputs/r1'

f1 = ddir+"/intensities/r1_c0_intensity.csv"
df1 = pd.read_csv(f1)
df1

         roi  weighted_centroid  weighted_local_centroid  mean_intensity
0          1      2.350810e-310            4.670650e-310       91.298986
1          2      2.267416e+130            2.267416e+130       95.414947
2          3      3.459803e+125            2.267416e+130       89.712408
3          4      2.267958e+130            1.485974e+135       89.865193
4          5      1.486329e+135            1.486329e+135       90.953012
...      ...                ...                      ...             ...
28223  28224      5.785498e-307            5.785498e-307       89.736064
28224  28225      5.785498e-307            5.785498e-307       90.844904
28225  28226      6.008005e-307            5.785501e-307       89.911169
28226  28227      5.785498e-307            6.230512e-307       89.573233
28227  28228      5.785501e-307            6.008008e-307       91.155698

[28228 rows x 4 columns]

In [3]:
f2 = ddir+"/v16384/intensities/r1_c0_intensity.csv"
df2 = pd.read_csv(f2)
df2

         roi  weighted_centroid  weighted_local_centroid  mean_intensity
0          1      2.332388e-310            4.654703e-310       91.298986
1          2      5.276718e+120            3.458976e+125       95.414947
2          3      2.266875e+130            3.458976e+125       89.712408
3          4      3.458976e+125            2.266875e+130       89.865193
4          5      3.458976e+125            3.458977e+125       90.953012
...      ...                ...                      ...             ...
28223  28224      6.008008e-307            6.008012e-307       89.736064
28224  28225      6.008008e-307            6.230519e-307       90.844904
28225  28226      6.230516e-307            6.230519e-307       89.911169
28226  28227      5.785498e-307            5.785498e-307       89.573233
28227  28228      6.008008e-307            5.785498e-307       91.155698

[28228 rows x 4 columns]

In [4]:
f3 = ddir+"/v8192/intensities/r1_c0_intensity.csv"
df3 = pd.read_csv(f3)
df3

         roi  weighted_centroid  weighted_local_centroid  mean_intensity
0          1      2.371646e-310            4.657603e-310       91.298986
1          2      2.267416e+130            2.267416e+130       95.414947
2          3      3.459803e+125            2.267416e+130       89.712408
3          4      2.267958e+130            1.485974e+135       89.865193
4          5      1.486329e+135            1.486329e+135       90.953012
...      ...                ...                      ...             ...
28223  28224      5.785498e-307            5.785498e-307       89.736064
28224  28225      5.785498e-307            5.785498e-307       90.844904
28225  28226      6.008005e-307            5.785501e-307       89.911169
28226  28227      5.785498e-307            6.230512e-307       89.573233
28227  28228      5.785501e-307            6.008008e-307       91.155698

[28228 rows x 4 columns]

In [5]:
f4 = ddir+"/old/intensities/r1_c0_intensity.csv"
df4 = pd.read_csv(f4)
df4

         roi  weighted_centroid  weighted_local_centroid  mean_intensity
0          1      2.344402e-310            4.686642e-310       91.298986
1          2      2.266875e+130            2.266875e+130       95.414947
2          3      3.458977e+125            2.266875e+130       89.712408
3          4      2.266875e+130            2.267416e+130       89.865193
4          5      2.267416e+130            1.486329e+135       90.953012
...      ...                ...                      ...             ...
28223  28224      5.785498e-307            6.008005e-307       89.736064
28224  28225      6.008005e-307            6.008005e-307       90.844904
28225  28226      6.008005e-307            6.008008e-307       89.911169
28226  28227      6.008012e-307            6.008008e-307       89.573233
28227  28228      5.785501e-307            5.785498e-307       91.155698

[28228 rows x 4 columns]

In [6]:
np.all(df1['mean_intensity'] == df2['mean_intensity'])
np.max(df1['mean_intensity'] - df4['mean_intensity'])

0.00021324493607721706

In [7]:
np.all(df1['mean_intensity'] == df3['mean_intensity'])
np.max(df1['mean_intensity'] - df4['mean_intensity'])

0.00021324493607721706

In [8]:
np.all(df1['mean_intensity'] == df4['mean_intensity'])
np.max(df1['mean_intensity'] - df4['mean_intensity'])

0.00021324493607721706

In [9]:
np.max(df1['mean_intensity'] - df4['mean_intensity'])

0.00021324493607721706